from typing import Iterable
from pydantic import BaseModel
from fastembed import TextEmbedding
from loguru import logger
from app.config import settings

model_cache: dict[str, TextEmbedding] = {}


def get_model(model_id: str) -> TextEmbedding:
    """Fetch the model from cache, or load it if not present."""

    if model_id not in model_cache:
        logger.info(f"Loading embedding model into memory: {model_id}")
        model_cache[model_id] = TextEmbedding(
            model_id, threads=settings.EMBEDDING_THREADS
        )
    return model_cache[model_id]


def preload_default_model():
    """Hook to pre-load the default model during startup."""
    logger.info("Preloading default embedding model...")
    get_model(settings.DEFAULT_EMBEDDING_MODEL)
    logger.info(
        f"Default embedding model {settings.DEFAULT_EMBEDDING_MODEL} preloaded successfully."
    )


class EmbeddingResult(BaseModel):
    vectors: list[list[float]]
    """Vectors generated by the model"""
    prompt_tokens: int
    """Token usage count for the input text"""
    model_used: str
    """Model used to generate the embeddings"""


def embed_text(
    texts: Iterable[str] | str, model_id: str = settings.DEFAULT_EMBEDDING_MODEL
) -> EmbeddingResult:
    try:
        model = get_model(model_id)
    except Exception as e:
        logger.error(f"Error initializing embedding model: {e}")
        raise

    try:
        # model.embed natively batches an iterable of documents giving an iterable of numpy arrays
        vectors = [vec.tolist() for vec in model.embed(texts,batch_size=settings.EMBEDDING_BATCH_SIZE)]

        # token_count returns an iterator of ints (tokens per document), so we sum them
        total_tokens = model.token_count(texts)

        return EmbeddingResult(
            vectors=vectors, prompt_tokens=total_tokens, model_used=model_id
        )
    except Exception as e:
        logger.error(f"Error generating embeddings: {e}")
        raise
