from typing import Iterable
from pydantic import BaseModel
from fastembed import TextEmbedding
from loguru import logger
from app.config import settings

DEFAULT_EMBEDDING_MODEL = settings.DEFAULT_EMBEDDING_MODEL


class EmbeddingResult(BaseModel):
    vectors: list[list[float]]
    """Vectors generated by the model"""
    prompt_tokens: int
    """Token usage count for the input text"""
    model_used: str
    """Model used to generate the embeddings"""


def embed_text(
    texts: Iterable[str] | str, model_id: str = DEFAULT_EMBEDDING_MODEL
) -> EmbeddingResult:
    try:
        model = TextEmbedding(model_id)
    except Exception as e:
        logger.error(f"Error initializing embedding model: {e}")
        raise

    try:
        # model.embed natively batches an iterable of documents giving an iterable of numpy arrays
        vectors = [vec.tolist() for vec in model.embed(texts)]

        # token_count returns an iterator of ints (tokens per document), so we sum them
        total_tokens = model.token_count(texts)

        return EmbeddingResult(
            vectors=vectors, prompt_tokens=total_tokens, model_used=model_id
        )
    except Exception as e:
        logger.error(f"Error generating embeddings: {e}")
        raise
