services:
  localembed:
    image: heshinth/localembed:latest-gpu
    pull_policy: always
    container_name: localembed-gpu
    ports:
      - "8000:8000"
    environment:
      - DEFAULT_EMBEDDING_MODEL=BAAI/bge-small-en-v1.5
      # - HF_TOKEN=your_token_here
      # - MODEL_CACHE_LIMIT=2
      # - EMBEDDING_THREADS=8
      # - BATCH_SIZE=256
    gpus: all
